src/Domain/Work/Entity/Work.php
<?php

declare(strict_types=1);

namespace App\Domain\Work\Entity;

use App\Domain\Guild\Entity\GuildSettings;
use App\Domain\Work\Repository\WorkRepository;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\CustomIdGenerator;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToOne;
use Symfony\Bridge\Doctrine\IdGenerator\UuidGenerator;
use Symfony\Component\Validator\Constraints\GreaterThanOrEqual;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\NotNull;

#[Entity(repositoryClass: WorkRepository::class)]
class Work
{
    #[Id, GeneratedValue(strategy: 'CUSTOM'), CustomIdGenerator(class: UuidGenerator::class)]
    #[Column(type: 'uuid', unique: true)]
    protected string $id;

    #[Column(type: 'string', length: 50)]
    #[NotBlank, Length(max: 50)]
    protected string $name;

    #[Column(type: 'text')]
    #[NotBlank]
    protected string $description;

    #[Column(type: 'datetime')]
    protected \DateTime $creationDate;

    #[Column(type: 'datetime')]
    #[NotNull, GreaterThanOrEqual('now')]
    protected \DateTime $dueDate;

    #[ManyToOne(targetEntity: GuildSettings::class)]
    #[JoinColumn(name: 'server_id', referencedColumnName: 'GuildId')]
    protected GuildSettings $guild;

    #[Column(type: 'string', length: 40, nullable: true)]
    protected ?string $messageId;

    #[Column(type: 'datetime', nullable: true)]
    protected ?\DateTime $recallDate;

    #[ManyToOne(targetEntity: WorkCategory::class, inversedBy: 'works')]
    #[JoinColumn(name: 'work_category_id')]
    private WorkCategory $work_category;

    public function __construct()
    {
        $this->creationDate = new \DateTime();
        $this->recallDate = null;
        $this->messageId = null;
    }

    public function getId(): string
    {
        return $this->id;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCreationDate(): \DateTime
    {
        return $this->creationDate;
    }

    public function getDueDate(): \DateTime
    {
        return $this->dueDate;
    }

    public function setDueDate(?\DateTime $dueDate): self
    {
        if ($dueDate !== null) {
            $this->dueDate = $dueDate;
        }

        return $this;
    }

    public function getWorkCategory(): WorkCategory
    {
        return $this->work_category;
    }

    public function setWorkCategory(WorkCategory $work_category): self
    {
        $this->work_category = $work_category;

        return $this;
    }

    public function getGuild(): GuildSettings
    {
        return $this->guild;
    }

    public function setGuild(GuildSettings $guild): self
    {
        $this->guild = $guild;

        return $this;
    }

    public function getMessageId(): ?string
    {
        return $this->messageId;
    }

    public function setMessageId(?string $messageId): self
    {
        $this->messageId = $messageId;

        return $this;
    }

    public function getRecallDate(): ?\DateTime
    {
        return $this->recallDate;
    }

    public function setRecallDate(?\DateTime $recallDate): self
    {
        $this->recallDate = $recallDate;

        return $this;
    }
}

templates/_head.html.twig
<meta charset="utf-8"/>
<link rel="icon" href="{{ asset('favicon.ico') }}"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<meta name="theme-color" content="#000000"/>
<meta name="description" content="Web site created using create-react-app"/>
<link rel="apple-touch-icon" href="{{ asset('favicon.png') }}"/>
<link rel="manifest" href="{{ asset('manifest.json') }}"/>
<title>Silvain.Eu | Monsieur Patate Bot</title>
{#<link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:ital,wght@0,300;0,700;1,300&family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;0,800;1,300;1,400;1,600;1,700;1,800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"#}
{#      rel="stylesheet">#}
<link rel="stylesheet" href="{{ asset('css/fontawesome/css/all.css') }}">
<meta name="turbo-cache-control" content="no-cache">

templates/_nav_left.html.twig
<nav id="nav-left" class="nav-left" data-turbo-permanent>

    <button id="nav-responsive_close">
        <i class="fas fa-times"></i>
        Fermer
    </button>

    <div class="nav-header">
        <div class="nav-header_img">
            {% if current_guild().icon is null %}
                <img src="{{ asset('favicon.png') }}" alt="Favicon">
            {% else %}
                <img src="{{ current_guild_icon() }}" alt="Favicon">
            {% endif %}
        </div>
        <div class="nav-header_content">
            <h1>{{ current_guild().name }}</h1>
            <p>
                <span class="dot-circle"
                      style="background-color: {{ current_user_highest_role(app.user).color|discord_color }}"></span>
                {{ current_user_highest_role(app.user).name }}
            </p>
        </div>
    </div>
    <div class="nav_left-content">
        <a class="menu-item" href="{{ path('index') }}">
            <div class="menu-item_icon"><i class="fas fa-home"></i></div>
            <div class="menu-item_content">Tableau de bord</div>
        </a>
        {% if is_granted("ROLE_WORK") %}
            <a class="menu-item" href="{{ path('work_add') }}">
                <div class="menu-item_icon"><i class="fas fa-plus"></i></div>
                <div class="menu-item_content">Ajouter un devoir</div>
            </a>
        {% endif %}
        <a class="menu-item" href="{{ path('planning_index') }}">
            <div class="menu-item_icon"><i class="fas fa-calendar-alt"></i></div>
            <div class="menu-item_content">Emplois du temps</div>
        </a>
        {% if is_granted("ROLE_ADMIN_DISCORD") %}
            <a class="menu-item" href="{{ path('config') }}">
                <div class="menu-item_icon"><i class="fas fa-cogs"></i></div>
                <div class="menu-item_content">Configuration</div>
            </a>
            <a class="menu-item" href="{{ path('config_database') }}">
                <div class="menu-item_icon"><i class="fas fa-folder"></i></div>
                <div class="menu-item_content">Données</div>
            </a>
        {% endif %}
    </div>
</nav>

templates/_nav_top.html.twig
<div class="nav_top" data-turbo-permanent>
    <div class="nav-top_item">
        <button id="nav-responsive_open" data-turbo-permanent>
            <i class="fas fa-bars"></i>
        </button>
    </div>
    <div class="nav-top_spacer"></div>

    <div class="nav-top_profile">
        <img src="{{ user_discord_avatar(app.user) }}" alt="">
        <div class="nav-top_profile-content">
            <p>{{ user_discord_username() }}</p>
        </div>
    </div>

    <div class="nav-top_item">
        <a href="{{ path('logout') }}">
            <i class="fas fa-sign-out-alt"></i>
        </a>
    </div>
</div>

templates/_themes.html.twig
{% use 'form_div_layout.html.twig' %}

{%- block form_errors -%}
    {%- if errors|length > 0 -%}
        <ul class="form-error">
            {%- for error in errors -%}
                <li>{{ error.message }}</li>
            {%- endfor -%}
        </ul>
    {%- endif -%}
{%- endblock form_errors -%}

{%- block form -%}
    {{ form_start(form) }}
    <div class="form-row text-">
        {{- form_errors(form) -}}
    </div>
    {% for child in form|filter(child => not child.rendered) %}
        {{- form_row(child) -}}
    {% endfor %}
    {{ form_end(form) }}
{%- endblock form -%}

{%- block form_row -%}
    {% set row_attr = row_attr|merge({class : row_attr.class|default('form-group')}) %}
    {%- set widget_attr = {required : false} -%}
    {%- if help is not empty -%}
        {%- set widget_attr = {attr: {'aria-describedby': id ~"_help"}} -%}
    {%- endif -%}
    <div{% with {attr: row_attr} %}{{ block('attributes') }}{% endwith %}>
        {{- form_label(form) -}}
        {{- form_widget(form, widget_attr) -}}
        {{- form_help(form) -}}
        {{- form_errors(form) -}}
    </div>
{%- endblock form_row -%}

{%- block button_row -%}
    {%- set row_attr = row_attr|merge({class: (row_attr.class|default('form-submit'))|trim}) -%}
    {{- parent() -}}
{% endblock %}

{%- block button_widget -%}
    {%- set attr = attr|merge({class: (attr.class|default('') ~ ' btn')|trim}) -%}
    {{- parent() -}}
{%- endblock button_widget -%}

{%- block checkbox_row -%}
    {% set row_attr = row_attr|merge({class : row_attr.class|default('form-check')}) %}
    {%- set widget_attr = {required : false} -%}
    {%- if help is not empty -%}
        {%- set widget_attr = {attr: {'aria-describedby': id ~"_help"}} -%}
    {%- endif -%}
    <div{% with {attr: row_attr} %}{{ block('attributes') }}{% endwith %}>
        {{- form_widget(form, widget_attr) -}}
        {% with {"label_html" : true} %}{{- block('form_label') -}}{% endwith %}
        {{- form_help(form) -}}
        {{- form_errors(form) -}}
    </div>

{%- endblock checkbox_row -%}


{%- block choice_widget_expanded -%}
    {%- for child in form %}
        <div {% with {attr: row_attr|merge({class: (row_attr.class|default('') ~ ' form-check')|trim})} %}{{ block('widget_container_attributes') }}{% endwith %} >
            {{- form_widget(child) -}}
            {{- form_label(child, null, {translation_domain: choice_translation_domain}) -}}
        </div>
    {% endfor %}
{%- endblock choice_widget_expanded -%}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    {{ vite_asset('app.js', []) }}
    {% include '_head.html.twig' %}
</head>


<body>

{% include '_nav_left.html.twig' %}

<div class="main-content">
    {% include '_nav_top.html.twig' %}

    <main>
        {% block content %}{% endblock %}
    </main>

    <footer data-turbo-permanent>
        {% block footer %}{% endblock footer %}
        <p><a href="{{ path('legal_notice') }}">Mentions légales</a></p>
        <p>Copyright © Ludwig SILVAIN {{ "now"|date("Y") }}</p>
    </footer>
</div>

{% block script %}{% endblock %}
</body>
</html>

templates/index.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div id="dashboard-index">
        {% if todayItems is not empty %}
            <div class="grid-rfull vstack px-2">
                <div class="hstack">
                    <h2><i class="fas fa-calendar-day"></i> Aujourd'hui</h2>
                </div>
                <div id="today-planning-item">
                    {% for i in todayItems %}
                        <div class="card" title="{{ i.description }}">
                            <div class="card-body">
                                <div class="vstack">
                                    <h3>{{ i.title }}</h3>
                                    <p class="text-muted">{{ i.location }} - <b>{{ i.teacher }}</b></p>
                                </div>

                                <div class="planning-item-time">
                            <span>
                                <i class="fa fa-calendar-alt mr-2"></i>
                                {{ i.dateStart|format_datetime(pattern="EEE d MMM",locale='fr') }}
                            </span>
                                    <span>
                                    {{ i.dateStart|format_datetime(pattern="HH'h'mm",locale='fr') }}
                                    -
                                    {{ i.dateEnd|format_datetime(pattern="HH'h'mm",locale='fr') }}
                                </span>
                                </div>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        {% endif %}
        <div class="vstack">
            {% if lastMessage is not  null %}
                <div class="hstack stack-vcenter px-2">
                    <h2><i class="fas fa-bullhorn"></i> Dernière annonce</h2>
                </div>
                <div class="card mb-5">
                    <div class="card-body">
                        {% for embed in lastMessage.embeds %}
                            <div class="hstack stack-vcenter">
                                <h3>{{ embed.title }}</h3>
                                {% if embed.author is not null %}
                                    {% if embed.author.url is not null %}
                                        <a href="{{ embed.author.url }}" class="text-muted">{{ embed.author.name }}</a>
                                    {% else %}
                                        <span class="text-muted">{{ embed.author.name }}</span>
                                    {% endif %}

                                {% endif %}

                                <div class="stack-spacer"></div>
                                <span><i class="fa fa-calendar-alt mr-2"></i> {{ lastMessage.dateSend|format_datetime(pattern="EEE d MMM HH'h'mm",locale='fr') }}</span>
                            </div>
                            {{ embed.content|nl2br|markdown_to_html }}
                        {% endfor %}
                    </div>
                </div>
            {% endif %}

            <div class="hstack stack-vcenter px-2">
                <h2><i class="fas fa-briefcase"></i> Devoirs</h2>
                <div class="stack-spacer"></div>
                <a href="{{ path('work_add') }}" class="btn btn-small">Ajouter</a>
            </div>
            {% for w in works %}
                <div class="card">
                    <div class="card-body">
                        <div class="hstack stack-vcenter">
                            <h3><a href="{{ path('work_edit', {'id': w.id}) }}">{{ w.name }}</a></h3>
                            <span class="text-muted">{{ w.workCategory.name }}</span>
                            <div class="stack-spacer"></div>
                            <span><i class="fa fa-calendar-alt mr-2"></i> {{ w.dueDate|format_datetime(pattern="EEE d MMM HH'h'mm",locale='fr') }}</span>
                        </div>
                        <div class="text-justify">
                            {{ w.description|markdown_to_html }}
                        </div>
                    </div>
                </div>
            {% else %}
                <p class="text-center">Pas de devoirs :(</p>
            {% endfor %}
        </div>
        <div class="vstack" id="next-planning-item">
            <div class="hstack stack-vcenter px-2">
                <h2><i class="fas fa-business-time"></i> Emplois du temps</h2>
            </div>
            {% if screen is not null %}
                <div class="planning-screen-img">
                   <div>
                       <img src="{{ path('planning_screen', {"week": screen.week,"year": screen.year}) }}"
                            class="w-100"
                            alt="{{ screen.week }}-{{ screen.year }}">
                   </div>
                    <p class="text-muted text-right">
                        {{ screen_start|format_datetime(pattern="d MMM",locale='fr') }} {{ screen_start|date("Y") }}
                        <i class="fas fa-long-arrow-alt-right"></i>
                        {{ screen_end|format_datetime(pattern="d MMM",locale='fr') }} {{ screen_end|date("Y") }}
                    </p>
                </div>
            {% endif %}
            {% for i in items %}
                <div class="card mb-3" title="{{ i.description }}">
                    <div class="card-body">
                        <div class="vstack">
                            <h3>{{ i.title }}</h3>
                            <p class="text-muted">{{ i.location }} - <b>{{ i.teacher }}</b></p>
                        </div>

                        <div class="planning-item-time">
                            <span>
                                <i class="fa fa-calendar-alt mr-2"></i>
                                {{ i.dateStart|format_datetime(pattern="EEE d MMM",locale='fr') }}
                            </span>
                            <span>
                                    {{ i.dateStart|format_datetime(pattern="HH'h'mm",locale='fr') }}
                                    -
                                    {{ i.dateEnd|format_datetime(pattern="HH'h'mm",locale='fr') }}
                                </span>
                        </div>

                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block script %}
    <script>
        document.querySelectorAll("#next-planning-item .planning-screen-img").forEach(x => x.addEventListener("click", () => x.classList.toggle("planning-screen-img-open")))
    </script>
    {#    <script> #}
    {#        const eventSource = new EventSource("{{ mercure('https://example.com/books/1')|escape('js') }}"); #}
    {#        eventSource.onmessage = event => { #}
    {#        //     Will be called every time an update is published by the server #}
    {#            console.log(JSON.parse(event.data)); #}
    {#        } #}
    {#    </script> #}
{% endblock %}